#!/usr/bin/env python3
"""Regenerate the palette parity fixture.

`PaletteSheet.swift` and `build-style-packs.py`'s `sheet()` are the same
derivation written twice — eight colours in, a whole map's worth of layer styles
out. Two copies of one function drift, and the drift is invisible: a green four
units off looks like a green. This fixture is the script's answer, and
`PaletteTests` compares every layer and every channel of the Swift engine
against it.

**This script did not exist.** The fixture was generated by importing the build
script as a module -- the `__pycache__` line in `.gitignore` is the fossil of it
-- from something nobody committed, so the one artefact that keeps two engines
honest could not be reproduced. Adding a layer to the pair meant hand-editing
JSON or leaving the layer unchecked.

Run from the repository root:

    python3 Scripts/generate-palette-parity-fixture.py
    python3 Scripts/generate-palette-parity-fixture.py --check

`--check` regenerates and diffs without writing, which is what to run after
touching either engine.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "Tests/HipparchusRenderTests/Fixtures/palette-parity.json"
SCRIPT = ROOT / "Scripts/build-style-packs.py"


def build_style_packs():
    """The pack builder, imported as a module.

    Its filename has hyphens in it, so it cannot be imported by name; this is
    the same loader dance the original generation must have done.
    """
    spec = importlib.util.spec_from_file_location("build_style_packs", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def palettes(packs) -> dict[str, dict]:
    """The palettes the fixture pins, with the colours the Swift twins use.

    Three of the seventeen, and deliberately these three: `Tsevis Daylight` is
    the pale sheet the derivation was designed against, `Admiralty` is the one
    whose `seaFill`, `roadScale` and `contourWeight` are all off the default, and
    `Slate` is dark.

    **The dark one was added after a bug that only a dark sheet could have.**
    The depth ramp was named rather than measured — one end "toward ink", the
    other "toward ground" — and on a dark palette the ink is pale and the paper
    near-black, so five of the seventeen drew deep water bright. Two light
    palettes could not catch it: they agree with the naming. Any derivation that
    asks "is this light or dark" needs a sheet of each on the pin, or it is
    pinned only where it was already right.

    The Nautical pack overrides four layers *after* calling `sheet()` -- a
    heavier sounding, a firmer coast, quieter buildings and summits. Those are
    the pack's own emphasis and not the derivation, so they are deliberately not
    applied here: what this fixture pins is the shared function.
    """
    mix = packs.mix
    WHITE, BLUE, INK, TURQUOISE = packs.WHITE, packs.BLUE, packs.INK, packs.TURQUOISE

    paper = (247, 241, 224)
    chart_ink = (26, 58, 82)
    shallow = (176, 214, 224)

    return {
        "Tsevis Daylight": packs.sheet(
            ground=mix(WHITE, BLUE, 0.04), ink=mix(BLUE, INK, 0.55),
            water=TURQUOISE, land=BLUE, road=WHITE,
            roadCasing=mix(BLUE, WHITE, 0.62),
            vegetation=mix(TURQUOISE, mix(WHITE, INK, 0.25), 0.55),
            contour=mix(BLUE, WHITE, 0.55),
        ),
        "Admiralty": packs.sheet(
            ground=paper, ink=chart_ink, water=shallow,
            land=mix(paper, (198, 186, 150), 0.55),
            road=mix(paper, chart_ink, 0.35), roadCasing=paper,
            vegetation=mix(paper, (170, 180, 140), 0.35),
            contour=mix(paper, chart_ink, 0.30),
            roadScale=0.55, contourWeight=1.6,
        ),
        # Dark paper, pale ink: the polarity every "is this light or dark"
        # derivation turns on. Colours copied from `Palettes.swift`.
        "Slate": packs.sheet(
            ground=(30, 34, 38), ink=(226, 232, 236), water=(52, 76, 92),
            land=(58, 64, 70), road=(188, 196, 202), roadCasing=(24, 28, 32),
            vegetation=(58, 78, 62), contour=(96, 108, 118),
        ),
    }


def report(old: dict, new: dict) -> list[str]:
    """What moved, in words rather than as a wall of JSON."""
    notes = []
    for name in sorted(set(old) | set(new)):
        before, after = old.get(name, {}), new.get(name, {})
        added = sorted(set(after) - set(before))
        removed = sorted(set(before) - set(after))
        changed = sorted(
            layer for layer in set(before) & set(after)
            if before[layer] != after[layer]
        )
        for layer in added:
            notes.append(f"{name}: + {layer}")
        for layer in removed:
            notes.append(f"{name}: - {layer}")
        for layer in changed:
            notes.append(f"{name}: ~ {layer}")
    return notes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="report differences without writing")
    args = parser.parse_args()

    fixture = palettes(build_style_packs())
    existing = json.loads(OUTPUT.read_text()) if OUTPUT.exists() else {}
    notes = report(existing, fixture)

    if args.check:
        for note in notes:
            print(note)
        if notes:
            print(f"\n{len(notes)} difference(s); run without --check to accept")
            return 1
        print("the fixture matches the script")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(fixture))
    layers = sum(len(styles) for styles in fixture.values())
    print(f"wrote {OUTPUT.relative_to(ROOT)}: "
          f"{len(fixture)} palettes x {layers // len(fixture)} layers")
    for note in notes:
        print(f"  {note}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
